### ISSUE TITLE
Roadmap / TODO list

### ISSUE THREAD

**Issue by AnthonyMichaelTDM** [lorenzoc25/rudis#4]
It'd be helpful for people looking to contribute if there was a roadmap or better todo list type thing with a more detailed list of tasks that need to be completed

(opening issues is another option, and may be more ergonomic)

**Comment by lorenzoc25** [comment]
Thanks for the suggestion! I think that's a great idea and I would do that shortly.

**Comment by lorenzoc25** [comment]
I've added some further descriptions to the TODO/Roadmap in issues section
